include:
  - proxy.yaml
services:
  db:
    image: mysql:8
    networks:
      backend:
        ipv4_address: 172.20.0.10
    env_file:
      ".env"
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      ".env"
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    networks:
      backend:
        ipv4_address: 172.20.0.5
    ports:
      - "5000:5000"
    restart: on-failure
